stages:
  - mirror


mirror repository:
    stage: mirror
    allow_failure: true
    variables:
      REPO: "git@github.com:quantum-tinkerer/research-docker.git"
    before_script:
      - mkdir /root/.ssh && chmod 700 /root/.ssh
      - ssh-keyscan -t rsa github.com >> /root/.ssh/known_hosts
      - echo "$DEPLOY_KEY" > /root/.ssh/id_rsa && chmod 600 /root/.ssh/id_rsa
    after_script:
      - rm -rf /root/.ssh
    script:
      - ORIGIN_URL=$(git config --get remote.origin.url)
      - cd $(mktemp -d); git clone --bare $ORIGIN_URL .
      - git push --mirror $REPO
