name: dev
channels:
  - kwant
  - ioam
  - conda-forge
dependencies:
  # general numerics
  - python=3.6
  - anaconda
  - kwant=dev
  - discretizer=0.4*
  - cython
  # fenics
  - fenics
  - mshr
  # plotting and serialization
  - deepdish
  - plotly
  # parallell computing
  - dill
  - distributed
  - hpc05
  - ipyparallel
  # other
  - line_profiler
  - feedparser
  - pytest-flakes
  - python-graphviz
  - xarray
  - pip:
    - git+https://github.com/ioam/holoviews.git
